### ISSUE TITLE
Remove the localBiblio for LDML?

### ISSUE THREAD

**Issue by xfq** [w3c/ltli#13]
Since it is possible to use `[[UTS35]]` to refer to LDML in ReSpec without adding a custom entry in `localBiblio`.

**Comment by aphillips** [comment]
Per discussion in telecon of 2020-10-08., won't change to [[UTS35]]

**Comment by xfq** [comment]
The disadvantage of this is that if the editor of LDML is changed, we need to update our custom entry and it is easy to forget. But since it is not a big issue, I am OK with closing it.
