### ISSUE TITLE
Use of HTTP Accept-Language header for a locale model.

### ISSUE THREAD

**Issue by r12a** [w3c/ltli#26]
https://w3c.github.io/ltli/#dfn-locale-aware

> Historically, locales were identified by the programming language or operating environment of the user. This application-specific identifier was often inferred from language tags. For example, an implementation could map a language tag from an existing protocol, such as HTTP's Accept-Language header, to its locale model.

What if the header value was a list of language tags – that wouldn't work. Perhaps the current wording makes this seem like a too-plausible option.  It is also problematic if not working over http.  Do we have a better example?

**Comment by aphillips** [comment]
Sure it could work and there is nothing implausible about it. In fact, that's actually how locales are set in many applications. Accept-Language is what's called a "language priority list" and one can (and does) do language negotiation to match that to available locales. It's actually an important example.

I could reword the text to include language priority lists and language negotiation, but the actual point, though, is to equate language tags with locales (including older stuff like `de_CH.utf8` and `AMERICAN_AMERICA.WE8MSWIN1252`--or even MS Windows LCIDs, which pack the information into bits, e.g. `en-US` == `0x0409`).

I do think the text is trying to do a couple of things and maybe getting ahead of itself. Perhaps:

> Historically different programming languages or operating environments defined their own locale identifiers. Some examples include POSIX locale identifiers, such as `de_CH.utf8` or `en_US.iso8869_1` or Oracle database's IDs, such as `AMERICAN_AMERICA.AL32UTF8`. These application-specific identifiers, however, were usually based on the same concepts as language tags and could be inferred from language tags.

I can then move the A-L stuff under language negotiation.

**Comment by r12a** [comment]
Ah, I thought you were referring to the use of Content-Language header, rather than the Accept-Language header. Ok, closing this.
